// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	Content     string `json:"content"`
	IsPublished *bool  `json:"is_published,omitempty"`
	Title       string `json:"title"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    int     `json:"code"`
		Details *string `json:"details,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
	Success bool `json:"success"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Data    []map[string]interface{} `json:"data"`
	Message *string                  `json:"message,omitempty"`
	Meta    struct {
		Page       int `json:"page"`
		PerPage    int `json:"per_page"`
		Total      int `json:"total"`
		TotalPages int `json:"total_pages"`
	} `json:"meta"`
	Success bool `json:"success"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken The refresh token to use for obtaining a new access token
	RefreshToken string `json:"refresh_token"`
}

// Response defines model for Response.
type Response struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
	Success bool                    `json:"success"`
}

// UpdatePostRequest defines model for UpdatePostRequest.
type UpdatePostRequest struct {
	Content     *string `json:"content,omitempty"`
	IsPublished *bool   `json:"is_published,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Username *string              `json:"username,omitempty"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// AuthorId Filter by author ID
	AuthorId *openapi_types.UUID `form:"author_id,omitempty" json:"author_id,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshTokenRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = CreateUserRequest

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = CreatePostRequest

// PutPostsIdJSONRequestBody defines body for PutPostsId for application/json ContentType.
type PutPostsIdJSONRequestBody = UpdatePostRequest

// PutUsersProfileJSONRequestBody defines body for PutUsersProfile for application/json ContentType.
type PutUsersProfileJSONRequestBody = UpdateUserRequest
